#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$commands = [
    __DIR__.'/nginx.sh',
];
$app = new Symfony\Component\Console\Application('Larahost Laravel Installer', 'v2.0.0');
$app->add(new Ankitjain28may\Larahost\LarahostCommand($commands));

$app->run();
